/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package activej.test;

import java.util.concurrent.ThreadLocalRandom;

import io.activej.http.AsyncServlet;
import io.activej.http.HttpMethod;
import io.activej.http.HttpResponse;
import io.activej.http.RoutingServlet;
import io.activej.inject.annotation.Provides;
import io.activej.launcher.Launcher;
import io.activej.launchers.http.HttpServerLauncher;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App extends HttpServerLauncher {
    private static final Logger LOGGER = LoggerFactory.getLogger("Test Server");

    @Provides
    public AsyncServlet servlet() {
        return RoutingServlet.create()
                .map(HttpMethod.GET,
                        "/random",
                        request -> HttpResponse
                                .ok200()
                                .withPlainText(String.valueOf(ThreadLocalRandom.current().nextInt()))
                );
    }

    public static void main(String[] args) throws Exception {
        Launcher launcher = new App();
        launcher.launch(args);
    }
}
